### ISSUE TITLE
Add functionality to buttons on HOME PAGE

### ISSUE THREAD

**Issue by GrimmeDev** [GrimmeDev/BreakAway#13]
-Hide the ADDRESS input area until after the user has selected one of the main 3 buttons

-Write JS code that hides the buttons NOT selected by the user

-Unhide the ADDRESS input area until the user has selected a button

-Add functionality for the refresh button

**Comment by GrimmeDev** [comment]
Functionality added.

**Comment by hallewehmeyer** [comment]
looks good!
